import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import GlobalLoader from '@/components/global/loader/GlobalLoader'
import RouteLoader from '@/components/global/loader/RouteLoader'
import Toaster from '@/components/global/Toaster'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-background text-foreground`}>
        <RouteLoader />
        <GlobalLoader />
        <Toaster />
        <div className="min-h-screen flex flex-col">
          {/* <Background /> */}
          <div className="fixed inset-0 -z-10">
            <div className="absolute inset-0 bg-background" />

            {/* subtle glow */}
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(99,102,241,0.12),transparent_40%)]" />
          </div>
          {/* <Header /> */}
          <main className="flex-1">{children}</main>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  )
}
